trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    version: '6.x'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- script: 'dotnet restore Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj -- -f net6.0'
  displayName: 'Restore project dependencies'

- script: 'dotnet build Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj -f net6.0 --no-restore --configuration Release'
  displayName: 'Build the project - Release'

- script: 'dotnet publish Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj -f net6.0 --no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
  displayName: 'Publish the project - Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()